# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

data = torch.rand((7,7))

# Create random tensor
x_data = torch.tensor(data)
x_data


<ipython-input-1-3fd6303a336a>:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_data = torch.tensor(data)


tensor([[0.3501, 0.4772, 0.0530, 0.3075, 0.2810, 0.9470, 0.0589],
        [0.3273, 0.5002, 0.8613, 0.9439, 0.1292, 0.5935, 0.5050],
        [0.8566, 0.5416, 0.9537, 0.6768, 0.0657, 0.1314, 0.5948],
        [0.1881, 0.8311, 0.9098, 0.3075, 0.3653, 0.0035, 0.1591],
        [0.7404, 0.2120, 0.2843, 0.4514, 0.1232, 0.6861, 0.4411],
        [0.2190, 0.4971, 0.5342, 0.3909, 0.1734, 0.4477, 0.4969],
        [0.9956, 0.4193, 0.3502, 0.9849, 0.1561, 0.3597, 0.2418]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
m1 = torch.rand((1,7))
m2 = torch.rand((1,7))
# Perform matrix multiplication
print(x_data@m2.T)
print(x_data@m1.T)


tensor([[1.1609],
        [1.7515],
        [1.4717],
        [1.5964],
        [0.9945],
        [1.2220],
        [1.3238]])
tensor([[1.3233],
        [2.4503],
        [2.1258],
        [1.7324],
        [1.4666],
        [1.7071],
        [1.6543]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
seed = 0
torch.manual_seed(seed)

# Create two random tensors
m1 = torch.rand((1,7))
# torch.manual_seed(seed)
m2 = torch.rand((1,7))

# Matrix multiply tensors
print(x_data@m1.T)
print(x_data@m2.T)


tensor([[1.3013],
        [1.4111],
        [1.4100],
        [1.0454],
        [1.3042],
        [1.1702],
        [1.3718]])
tensor([[0.8160],
        [1.5457],
        [1.9836],
        [1.4036],
        [1.2369],
        [1.0606],
        [1.7602]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(seed=1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.cuda.manual_seed(1234)
# Check for access to GPU
if torch.cuda.is_available():
  t1 = torch.rand((2,3)).to("cuda")
  t2 = torch.rand((2,3)).to("cuda")

# Create two random tensors on GPU
print(t1)
print(t2)


tensor([[0.2939, 0.5185, 0.6977],
        [0.8000, 0.1610, 0.2823]], device='cuda:0')
tensor([[0.6816, 0.9152, 0.3971],
        [0.8742, 0.4194, 0.5529]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
t3 = t1@t2.T
t3

tensor([[0.9519, 0.8601],
        [0.8048, 0.9229]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
print(t3.max())
# Find min
print(t3.min())

tensor(0.9519, device='cuda:0')
tensor(0.8048, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [11]:
# Find arg max
print(t3.argmax())

# Find arg min
print(t3.argmin())


tensor(0, device='cuda:0')
tensor(2, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
t4 = torch.rand((1,1,1,10))

# Remove single dimensions
t5 = t4.squeeze()

# Print out tensors and their shapes
print(t4, t4.shape)
print(t5, t5.shape)

tensor([[[[0.9527, 0.0362, 0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698,
           0.1507, 0.0317]]]]) torch.Size([1, 1, 1, 10])
tensor([0.9527, 0.0362, 0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507,
        0.0317]) torch.Size([10])
